name: WEC-DECIDER
title: WEC DECIDER
description: Wave Energy Converter Design Convergence Impact Driven 
  Engineering Roadmap
notebooks:
  - path: modules/CEM/make_additional_tech_csv.ipynb
    title: setup-sweep
  - path: modules/CEM/analyze_results.ipynb
    title: analyze-results
  - path: modules/CEM/iterate_locations.ipynb
    title: iterate-locations
  - path: modules/CEM/make_batch_csv.ipynb
    title: make-batch-csv
environments:
  decider:
    path: calkit-environment.yml
    kind: conda
pipeline:
  stages:
    setup-sweep:
      kind: jupyter-notebook
      environment: decider
      wdir:
      inputs: []
      outputs:
        - modules/CEM/data_east/wave_profiles
        - modules/CEM/data_east/settings/settings_management.yml
        - modules/CEM/data_east/scenario_input.csv
      notebook_path: modules/CEM/make_additional_tech_csv.ipynb
      html_storage: null
      executed_ipynb_storage: git
      cleaned_ipynb_storage: null
    analyze-results:
      kind: jupyter-notebook
      environment: decider
      wdir:
      inputs:
        - modules/CEM/data_CA/cases/Case_*/results_*/
        - modules/CEM/data_east/cases/Case_*/results_*/
        - modules/CEM/data_east/scenario_input.csv
      outputs: []
      notebook_path: modules/CEM/analyze_results.ipynb
      html_storage: null
      executed_ipynb_storage: git
      cleaned_ipynb_storage: null
