name: WEC-DECIDER
title: WEC DECIDER
description: Wave Energy Converter Design Convergence Impact Driven 
  Engineering Roadmap
notebooks:
  - path: modules/CEM/make_additional_tech_csv.ipynb
    title: setup-sweep
  - path: modules/CEM/analyze_results.ipynb
    title: analyze-results
  - path: modules/CEM/iterate_locations.ipynb
    title: iterate-locations
  - path: modules/CEM/make_batch_csv.ipynb
    title: make-batch-csv
environments:
  decider:
    path: envs/calkit-environment.yml
    kind: conda
dependencies:
  - WLSACCESSID:
      kind: env-var
      notes: Gurobi WLS Access ID (API key)
  - WLSSECRET:
      kind: env-var
      notes: Gurobi WLS Secret
  - LICENSEID:
      kind: env-var
      notes: Gurobi license ID
  - HSDS_API_KEY:
      kind: env-var
      notes: HSDS API key
  # - gurobi_cl:
  #     kind: app
  #     notes: Gurobi command line interface
pipeline:
  stages:
    setup-sweep:
      kind: jupyter-notebook
      environment: decider
      wdir:
      inputs:
        - modules/CEM/template/cost_mult_tech_map.yml
      outputs:
        - modules/CEM/data_east/wave_profiles
        - modules/CEM/data_east/settings/settings_management.yml
        - modules/CEM/data_east/scenario_input.csv
        - modules/CEM/data_east/settings/cost_mult_tech_map_updated.yml
      notebook_path: modules/CEM/make_additional_tech_csv.ipynb
      html_storage: git
      executed_ipynb_storage: git
      cleaned_ipynb_storage: null
    analyze-results:
      kind: jupyter-notebook
      environment: decider
      wdir:
      inputs:
      # - modules/CEM/data_CA/cases/Case_1/results/
      # - modules/CEM/data_CA/cases/Case_2/results/
      # - modules/CEM/data_CA/cases/Case_3/results/
      # - modules/CEM/data_CA/cases/Case_4/results/
      # - modules/CEM/data_CA/cases/Case_5/results/
        - modules/CEM/data_east/cases/Case_1/results/
        - modules/CEM/data_east/cases/Case_2/results/
        - modules/CEM/data_east/cases/Case_3/results/
        - modules/CEM/data_east/cases/Case_4/results/
        - modules/CEM/data_east/cases/Case_5/results/
        - modules/CEM/data_east/scenario_input.csv
      outputs: []
      notebook_path: modules/CEM/analyze_results.ipynb
      html_storage: git
      executed_ipynb_storage: git
      cleaned_ipynb_storage: null
