stages:
  powergenome-data-download:
    cmd: bash modules/CEM/get-powergenome-data.sh
    deps:
    - modules/CEM/get-powergenome-data.sh
    outs:
    - modules/CEM/data/
    - modules/CEM/data_CA/test_misc_gen_inputs.csv
    - modules/CEM/data_CA/test_demand_segments_voll.csv
    - modules/CEM/data_east/Reserves.csv
    - modules/CEM/data_east/emission_policies.csv
    - modules/CEM/data_east/misc_gen_inputs.csv
    - modules/CEM/data_east/resource_capacity_spur.csv
    - modules/CEM/data_east/demand_segments_voll.csv
