name: wec-decider
channels:
  - conda-forge
  - nrel
dependencies: 
  - python
  - pandas
  - numpy 
  - numpy-financial
  - scipy 
  - matplotlib 
  - h5pyd
  - requests
  - wecopttool
  - nrel-pysam
  - pyxdsm
  - openmdao
  - powergenome
  - gdown
#  - mpi4py 
#  - petsc4py
  - pip:
    - mhkit
    - gridstatus
    - wecopttool[geometry]
    - omxdsm@https://github.com/onodip/OpenMDAO-XDSM/tarball/master
#    - GenX
#    - pygenx