name: wec-decider
channels:
  - conda-forge
  - nrel
dependencies: 
  - python=3.9
  - pandas=1.5.2
  - numpy 
  - numpy-financial
  - scipy 
  - matplotlib 
  - h5pyd
  - requests
  - wecopttool
  - nrel-pysam
#  - mpi4py 
#  - petsc4py
  - pip:
    - mhkit
    - gridstatus
    - wecopttool[geometry]
    - openmdao[all]
#    - GenX
#    - pygenx