name: wec-decider
channels:
  - conda-forge
  - nrel
dependencies: 
  - python = 3.9
  - pandas
  - numpy=1.22
  - numpy-financial # econ module
  - scipy 
  - matplotlib 
  - h5pyd
  - requests
  # - wecopttool  # dynamics module
  - nrel-pysam  # econ module
  - pyxdsm      # diagram generation
  - openmdao
  #- powergenome # CEM module
  - gdown       # data for CEM module
  - ipykernel   # jupyter
  - pyjuliacall # julia for CEM module
  - pip
  - catalystcoop.pudl <= 2022.11.30, >= 0.6.0 # for powergenome (otherwise too new python version [3.11] is installed)
  - pyarrow = 7
  - pyogrio
#  - mpi4py 
#  - petsc4py
  - pip:
    - mhkit
    - capytaine==1.4.2
    - powergenome==0.6.2
    - gridstatus
    - wecopttool[geometry]
    - omxdsm@https://github.com/onodip/OpenMDAO-XDSM/tarball/master
    
#    - GenX
#    - pygenx