name: wec-decider
channels:
  - conda-forge
  - nrel
dependencies: 
  - python
  - pandas
  - numpy 
  - numpy-financial # econ module
  - scipy 
  - matplotlib 
  - h5pyd
  - requests
  - wecopttool  # dynamics module
  - nrel-pysam  # econ module
  - pyxdsm      # diagram generation
  - openmdao
  - powergenome # CEM module
  - gdown       # data for CEM module
  - ipykernel   # jupyter
  - pyjuliacall # julia for CEM module
#  - mpi4py 
#  - petsc4py
  - pip:
    - mhkit
    - gridstatus
    - wecopttool[geometry]
    - omxdsm@https://github.com/onodip/OpenMDAO-XDSM/tarball/master
#    - GenX
#    - pygenx