name: wec-decider
channels:
  - conda-forge
  - nrel
dependencies: 
  - python=3.9
  - pandas=1.5.2
  - numpy 
  - numpy-financial
  - scipy 
  - matplotlib 
  - h5pyd
  - requests
  - wecopttool
  - nrel-pysam
  - pyxdsm
  - openmdao
#  - mpi4py 
#  - petsc4py
  - pip:
    - mhkit
    - gridstatus==0.15.0
    - wecopttool[geometry]
    - omxdsm@https://github.com/onodip/OpenMDAO-XDSM/tarball/master
#    - GenX
#    - pygenx