settings_management:
  2030: &id001
    electrification:
      ref:
        electrification_scenario: REFERENCE ELECTRIFICATION - MODERATE TECHNOLOGY
          ADVANCEMENT
      med:
        electrification_scenario: MEDIUM ELECTRIFICATION - MODERATE TECHNOLOGY ADVANCEMENT
      high:
        electrification_scenario: HIGH ELECTRIFICATION - MODERATE TECHNOLOGY ADVANCEMENT
    carbon_constraint:
      low:
        emission_policies_fn: emission_policies_net_zero.csv
      med:
        emission_policies_fn: emission_policies_orig.csv
      high:
        emission_policies_fn: emission_policies_no_limit.csv
    wave_variability:
      Avail_zeta_0.05_omega_n_0.4_limited_200:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.4_limited_200.csv
      Avail_zeta_0.05_omega_n_0.5_limited_200:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.5_limited_200.csv
      Avail_zeta_0.05_omega_n_0.6_limited_200:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.6_limited_200.csv
      Avail_zeta_0.05_omega_n_0.7_limited_200:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.7_limited_200.csv
      Avail_zeta_0.1_omega_n_0.4_limited_200:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.4_limited_200.csv
      Avail_zeta_0.1_omega_n_0.5_limited_200:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.5_limited_200.csv
      Avail_zeta_0.1_omega_n_0.6_limited_200:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.6_limited_200.csv
      Avail_zeta_0.1_omega_n_0.7_limited_200:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.7_limited_200.csv
      Avail_zeta_0.2_omega_n_0.4_limited_200:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.4_limited_200.csv
      Avail_zeta_0.2_omega_n_0.5_limited_200:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.5_limited_200.csv
      Avail_zeta_0.2_omega_n_0.6_limited_200:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.6_limited_200.csv
      Avail_zeta_0.2_omega_n_0.7_limited_200:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.7_limited_200.csv
      Avail_zeta_0.05_omega_n_0.4_limited_400:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.4_limited_400.csv
      Avail_zeta_0.05_omega_n_0.5_limited_400:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.5_limited_400.csv
      Avail_zeta_0.05_omega_n_0.6_limited_400:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.6_limited_400.csv
      Avail_zeta_0.05_omega_n_0.7_limited_400:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.7_limited_400.csv
      Avail_zeta_0.1_omega_n_0.4_limited_400:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.4_limited_400.csv
      Avail_zeta_0.1_omega_n_0.5_limited_400:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.5_limited_400.csv
      Avail_zeta_0.1_omega_n_0.6_limited_400:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.6_limited_400.csv
      Avail_zeta_0.1_omega_n_0.7_limited_400:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.7_limited_400.csv
      Avail_zeta_0.2_omega_n_0.4_limited_400:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.4_limited_400.csv
      Avail_zeta_0.2_omega_n_0.5_limited_400:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.5_limited_400.csv
      Avail_zeta_0.2_omega_n_0.6_limited_400:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.6_limited_400.csv
      Avail_zeta_0.2_omega_n_0.7_limited_400:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.7_limited_400.csv
      Avail_zeta_0.05_omega_n_0.4_limited_600:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.4_limited_600.csv
      Avail_zeta_0.05_omega_n_0.5_limited_600:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.5_limited_600.csv
      Avail_zeta_0.05_omega_n_0.6_limited_600:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.6_limited_600.csv
      Avail_zeta_0.05_omega_n_0.7_limited_600:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.7_limited_600.csv
      Avail_zeta_0.1_omega_n_0.4_limited_600:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.4_limited_600.csv
      Avail_zeta_0.1_omega_n_0.5_limited_600:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.5_limited_600.csv
      Avail_zeta_0.1_omega_n_0.6_limited_600:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.6_limited_600.csv
      Avail_zeta_0.1_omega_n_0.7_limited_600:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.7_limited_600.csv
      Avail_zeta_0.2_omega_n_0.4_limited_600:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.4_limited_600.csv
      Avail_zeta_0.2_omega_n_0.5_limited_600:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.5_limited_600.csv
      Avail_zeta_0.2_omega_n_0.6_limited_600:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.6_limited_600.csv
      Avail_zeta_0.2_omega_n_0.7_limited_600:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.7_limited_600.csv
      Avail_zeta_0.05_omega_n_0.4_limited_800:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.4_limited_800.csv
      Avail_zeta_0.05_omega_n_0.5_limited_800:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.5_limited_800.csv
      Avail_zeta_0.05_omega_n_0.6_limited_800:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.6_limited_800.csv
      Avail_zeta_0.05_omega_n_0.7_limited_800:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.7_limited_800.csv
      Avail_zeta_0.1_omega_n_0.4_limited_800:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.4_limited_800.csv
      Avail_zeta_0.1_omega_n_0.5_limited_800:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.5_limited_800.csv
      Avail_zeta_0.1_omega_n_0.6_limited_800:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.6_limited_800.csv
      Avail_zeta_0.1_omega_n_0.7_limited_800:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.7_limited_800.csv
      Avail_zeta_0.2_omega_n_0.4_limited_800:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.4_limited_800.csv
      Avail_zeta_0.2_omega_n_0.5_limited_800:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.5_limited_800.csv
      Avail_zeta_0.2_omega_n_0.6_limited_800:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.6_limited_800.csv
      Avail_zeta_0.2_omega_n_0.7_limited_800:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.7_limited_800.csv
      Avail_zeta_0.05_omega_n_0.4_limited_1000:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.4_limited_1000.csv
      Avail_zeta_0.05_omega_n_0.5_limited_1000:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.5_limited_1000.csv
      Avail_zeta_0.05_omega_n_0.6_limited_1000:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.6_limited_1000.csv
      Avail_zeta_0.05_omega_n_0.7_limited_1000:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.05_omega_n_0.7_limited_1000.csv
      Avail_zeta_0.1_omega_n_0.4_limited_1000:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.4_limited_1000.csv
      Avail_zeta_0.1_omega_n_0.5_limited_1000:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.5_limited_1000.csv
      Avail_zeta_0.1_omega_n_0.6_limited_1000:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.6_limited_1000.csv
      Avail_zeta_0.1_omega_n_0.7_limited_1000:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.1_omega_n_0.7_limited_1000.csv
      Avail_zeta_0.2_omega_n_0.4_limited_1000:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.4_limited_1000.csv
      Avail_zeta_0.2_omega_n_0.5_limited_1000:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.5_limited_1000.csv
      Avail_zeta_0.2_omega_n_0.6_limited_1000:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.6_limited_1000.csv
      Avail_zeta_0.2_omega_n_0.7_limited_1000:
        additional_technologies_fn: wave_profiles/Avail_zeta_0.2_omega_n_0.7_limited_1000.csv
    wave_cost:
      Wave_500:
        additional_new_gen:
        - Wave_500
      Wave_750:
        additional_new_gen:
        - Wave_750
      Wave_1000:
        additional_new_gen:
        - Wave_1000
      Wave_1250:
        additional_new_gen:
        - Wave_1250
      Wave_1500:
        additional_new_gen:
        - Wave_1500
  2045: *id001
